version: 1
disable_existing_loggers: False

formatters:
  default:
    format: '#{levelname:8} {name}: {funcName} - {message}'
    style: '{'
  formatter_1:
    format: '[{asctime}] #{levelname:8} {filename}: {lineno} - {funcName} -> {message}'
    style: '{'

filters:

  debug_info_filter:
    (): app.logging_config.loggers_filter.DebugInfoLogFilter
  warning_error_critical_filter:
    (): app.logging_config.loggers_filter.WarningErrorCritical

handlers:

  stderr:
    class: logging.StreamHandler
    formatter: default
    filters: [debug_info_filter]

  war_err_crit_file:
    class: logging.FileHandler
    filename: C:/Users/Redmi/Log/war_err_crit.log
    mode: w
    encoding: utf-8
    level: WARNING
    formatter: formatter_1
    filters: [warning_error_critical_filter]


root:
  level: DEBUG
  formatter: default
  handlers: [stderr, war_err_crit_file]
