version: 1
disable_existing_loggers: False

formatters:
  default:
    format: '#{levelname:8} {name}: {funcName} - {message}'
    style: '{'
  formatter_1:
    format: '[{asctime}] #{levelname:8} {filename}: {lineno} - {funcName} -> {message}'
    style: '{'

filters:

  debug_info_filter:
    (): logging_config.loggers_filter.DebugInfoLogFilter
  warning_error_critical_filter:
    (): logging_config.loggers_filter.WarningErrorCritical

handlers:

  stderr:
    class: logging.StreamHandler
    formatter: default
    filters: [debug_info_filter]

  war_err_crit_file:
    class: logging.FileHandler
    filename: war_err_crit.log
    mode: a
    encoding: utf-8
    formatter: formatter_1
    filters: [warning_error_critical_filter]

loggers:
  app.tg_bot.template.tg_bot:
    handlers: [war_err_crit_file]

root:
  level: DEBUG
  formatter: default
  handlers: [stderr]
